site_name: PennCNV
site_url: http://penncnv.openbioinformatics.org/
repo_url: http://github.com/WGLab/penncnv/
repo_name: GitHub
site_description: PennCNV software distribution site
site_author: Kai Wang, et al
#site_favicon: favicon.ico      #favicon.ico is removed from MkDocs; To use a different icon, create an img subdirectory in your docs_dir and copy your custom favicon.ico file to that directory
copyright: 2007-2022 PennCNV
google_analytics: ['UA-7565671-1', 'www.openbioinformatics.org/penncnv']

docs_dir: docs
#include_search: true
#use_absolute_urls: true
#use_directory_urls: false

nav:

- Home: 'index.md'
- User Guide:
    - 'Download PennCNV': 'user-guide/download.md'
    - 'Install PennCNV': 'user-guide/install.md'
    - 'Quick Start-Up Guide': 'user-guide/startup.md'
    - 'Prepare Input Files': 'user-guide/input.md'
    - 'CNV calling': 'user-guide/test.md'
    - 'Trio-based CNV calling': 'user-guide/trio.md'
    - 'Joint-based CNV calling': 'user-guide/joint.md'
    - 'de novo CNV calling': 'user-guide/denovo.md'
    - 'Validation-based CNV calling': 'user-guide/validation.md'
    - 'CNV annotation': 'user-guide/annotation.md'
    - 'CNV visualization': 'user-guide/visualization.md'
    - 'PennCNV-Affy': 'user-guide/affy.md'
    - 'PennCNV Plug-in': 'user-guide/plugin.md'
- Misc:
    - 'FAQ': 'misc/faq.md'
    - 'Version History': 'misc/version_history.md'
    - 'Credit': 'misc/credit.md'
    - 'How to Contribute': 'misc/contributing.md'





